### ISSUE TITLE
Windows: ImportError: No module named termios

### ISSUE THREAD

**Issue by ghost** [xolox/python-capturer#4] opened 2016-09-04 04:30 UTC
I am getting following exception while using capturer at https://github.com/binit92/OpenWARP

running build_ext
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    from openwarp.web import WebController
  File "C:\Users\binit92\Downloads\OpenWARP-master\OpenWARP-master\source\openwarpgui\openwarp\web.py", line 27, in <module>
    from openwarp import services
  File "C:\Users\binit92\Downloads\OpenWARP-master\OpenWARP-master\source\openwarpgui\openwarp\services.py", line 44, in <module>
    from capturer import CaptureOutput
  File "C:\Anaconda\lib\site-packages\capturer__init__.py", line 10, in <module

> ```
> import pty
> ```
> 
>   File "C:\Anaconda\lib\pty.py", line 11, in <module>
>     import tty
>   File "C:\Anaconda\lib\tty.py", line 5, in <module>
>     from termios import *
> ImportError: No module named termios

**Comment by AnneTheAgile** [comment] 2016-09-20 20:49
@binit92 , it looks like the dependency does not yet support windows [1]. Maybe if you know of a fix you could send PR to either there or here. Alternatively, maybe Microsoft has added a feature that would help and/or if you upgrade to Win10.1 it would work? 

On OSX 10.11.6 it is working great for me. It is a terrific helper. 
Anne
1.[] ; ; ; X.36.9. pty — Pseudo-terminal utilities — Python 2.7.12 documentation ; ; https://docs.python.org/2/library/pty.html 
Because pseudo-terminal handling is highly platform dependent, there is code to do it only for Linux. (The Linux code is supposed to work on other platforms, but hasn’t been tested yet.)

**Comment by xolox** [comment] 2016-11-12 19:37
Hi Binit and thanks for the feedback. I created the _capturer_ package for use on UNIX systems with the specific goal of emulating a real terminal and to accomplish this I used the [pty](https://docs.python.org/2/library/pty.html) module. Even though this module is included in Python's standard library it is UNIX specific and so doesn't support Windows. This is mentioned in the readme:

> The use of [pty.openpty()](https://docs.python.org/2/library/pty.html#pty.openpty) means you need to be running in a UNIX like environment for capturer to work (Windows definitely isn't supported).

I don't know of any meaningful way to add Windows support to _capturer_, however I have made the supported operating systems more explicit by mentioning them in the introduction of the readme:

> The capturer package makes it easy to capture the stdout and stderr streams of the current process and subprocesses. Output can be relayed to the terminal in real time but is also available to the Python program for additional processing. It's currently tested on cPython 2.6, 2.7, 3.4, 3.5 and PyPy (2.7). **It's tested on Linux and Mac OS X and may work on other unixes but definitely won't work on Windows (due to the use of the platform dependent pty module).**

I'm going to close this issue now given that the lack of Windows support is "by design".

**Closed as completed by xolox** 2016-11-12 19:37 UTC
